import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';

const PA_SNAP_PDF_URL = 'https://www.pa.gov/content/dam/copapwp-pagov/en/dhs/documents/services/assistance/documents/benefits-applications/PA%20600%20FS%20SG%20%E2%80%94%20SNAP.pdf';

// Fallback: generate a clean structured PDF if the official form can't be fetched
async function generateFallbackPDF(data) {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  const addPage = () => {
    const page = pdfDoc.addPage([612, 792]);
    return page;
  };

  const page = addPage();
  const { width, height } = page.getSize();

  // Header
  page.drawRectangle({ x: 0, y: height - 80, width, height: 80, color: rgb(0.15, 0.39, 0.93) });
  page.drawText('PENNSYLVANIA SNAP APPLICATION', {
    x: 30, y: height - 35, size: 18, font: boldFont, color: rgb(1, 1, 1),
  });
  page.drawText('PA 600 FS — Supplemental Nutrition Assistance Program', {
    x: 30, y: height - 58, size: 11, font, color: rgb(0.9, 0.9, 1),
  });

  let y = height - 110;
  const lineH = 22;
  const labelX = 30;
  const valueX = 220;

  const section = (title) => {
    y -= 10;
    page.drawRectangle({ x: 25, y: y - 4, width: width - 50, height: 22, color: rgb(0.93, 0.96, 1) });
    page.drawText(title, { x: 30, y, size: 11, font: boldFont, color: rgb(0.15, 0.39, 0.93) });
    y -= lineH + 4;
  };

  const field = (label, value) => {
    if (!value) return;
    page.drawText(label + ':', { x: labelX, y, size: 9, font: boldFont, color: rgb(0.3, 0.3, 0.3) });
    page.drawText(String(value), { x: valueX, y, size: 10, font, color: rgb(0, 0, 0) });
    y -= lineH;
    if (y < 60) {
      const np = addPage();
      y = np.getSize().height - 60;
    }
  };

  section('APPLICANT INFORMATION');
  field('First Name', data.firstName);
  field('Last Name', data.lastName);
  field('Address', data.address);
  field('County', data.county);
  field('Phone', data.phone);
  field('Date of Application', new Date().toLocaleDateString());

  section('HOUSEHOLD MEMBERS');
  if (data.householdMembers && data.householdMembers.length > 0) {
    data.householdMembers.forEach((m, i) => {
      field(`Member ${i + 1} Name`, m.name);
      field(`  Date of Birth`, m.dob);
      field(`  Relationship`, m.relationship);
      field(`  U.S. Citizen`, m.usCitizen ? 'Yes' : 'No');
    });
  } else {
    page.drawText('No additional household members listed.', { x: labelX, y, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
    y -= lineH;
  }

  section('INCOME INFORMATION');
  if (data.monthlyIncome && data.monthlyIncome.length > 0) {
    data.monthlyIncome.forEach((inc, i) => {
      field(`Income Source ${i + 1}`, inc.source);
      field(`  Amount`, `$${inc.amount}`);
      field(`  Frequency`, inc.frequency);
    });
  } else {
    page.drawText('No income reported.', { x: labelX, y, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
    y -= lineH;
  }

  section('EXPENSES');
  if (data.expenses) {
    field('Monthly Rent', data.expenses.rent ? `$${data.expenses.rent}` : null);
    field('Monthly Mortgage', data.expenses.mortgage ? `$${data.expenses.mortgage}` : null);
    field('Monthly Utilities', data.expenses.utilities ? `$${data.expenses.utilities}` : null);
    field('Monthly Childcare', data.expenses.childcare ? `$${data.expenses.childcare}` : null);
  }

  section('SIGNATURE');
  y -= 10;
  page.drawText('I certify that the information provided is true and correct to the best of my knowledge.', {
    x: labelX, y, size: 9, font, color: rgb(0.3, 0.3, 0.3),
  });
  y -= lineH * 2;
  page.drawLine({ start: { x: labelX, y }, end: { x: labelX + 200, y }, thickness: 1, color: rgb(0, 0, 0) });
  page.drawText('Applicant Signature', { x: labelX, y: y - 14, size: 8, font, color: rgb(0.5, 0.5, 0.5) });
  page.drawLine({ start: { x: labelX + 250, y }, end: { x: labelX + 380, y }, thickness: 1, color: rgb(0, 0, 0) });
  page.drawText('Date', { x: labelX + 250, y: y - 14, size: 8, font, color: rgb(0.5, 0.5, 0.5) });
  page.drawText(new Date().toLocaleDateString(), { x: labelX + 250, y, size: 10, font, color: rgb(0, 0, 0) });

  // Footer
  const lastPage = pdfDoc.getPage(pdfDoc.getPageCount() - 1);
  lastPage.drawText('Generated by BenefitPath — benefitpath.web.app | PA DHS SNAP Program | PA 600 FS', {
    x: 30, y: 20, size: 8, font, color: rgb(0.6, 0.6, 0.6),
  });

  return pdfDoc;
}

export async function generateSnapPDF(extractedData) {
  let pdfDoc;
  let useOverlay = false;

  // Try to fetch the official PA SNAP form
  try {
    const response = await fetch(PA_SNAP_PDF_URL);
    if (response.ok) {
      const pdfBytes = await response.arrayBuffer();
      pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });
      useOverlay = true;
    } else {
      throw new Error('Could not fetch official form');
    }
  } catch (err) {
    console.warn('Could not load official PA SNAP PDF, generating structured form:', err.message);
    pdfDoc = await generateFallbackPDF(extractedData);
    const bytes = await pdfDoc.save();
    return bytes;
  }

  if (!useOverlay) {
    const bytes = await pdfDoc.save();
    return bytes;
  }

  // Overlay text on official PA SNAP form
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const pages = pdfDoc.getPages();

  const draw = (pageIndex, x, y, text, size = 9) => {
    if (pageIndex >= pages.length || !text) return;
    const page = pages[pageIndex];
    page.drawText(String(text), {
      x, y,
      size,
      font,
      color: rgb(0, 0, 0),
    });
  };

  const d = extractedData;
  const today = new Date().toLocaleDateString('en-US');

  // PAGE 1 — Personal info
  draw(0, 230, 648, d.firstName || '', 10);
  draw(0, 72, 648, d.lastName || '', 10);
  draw(0, 72, 620, d.address || '', 10);
  draw(0, 72, 595, d.county || '', 10);
  draw(0, 280, 595, d.phone || '', 10);

  // Household members table — page 1, starting at y:540, 20px rows
  const members = d.householdMembers || [];
  members.slice(0, 6).forEach((m, i) => {
    const rowY = 540 - i * 20;
    draw(0, 72, rowY, m.name || '', 9);
    draw(0, 220, rowY, m.relationship || '', 9);
    draw(0, 310, rowY, m.dob || '', 9);
    draw(0, 410, rowY, m.usCitizen ? 'Y' : 'N', 9);
  });

  // PAGE 2 — Income
  if (pages.length > 1) {
    const incomes = d.monthlyIncome || [];
    incomes.slice(0, 6).forEach((inc, i) => {
      const rowY = 680 - i * 20;
      draw(1, 72, rowY, inc.source || '', 9);
      draw(1, 350, rowY, inc.amount ? `$${inc.amount}` : '', 9);
      draw(1, 430, rowY, inc.frequency || '', 9);
    });
  }

  // PAGE 3 — Expenses
  if (pages.length > 2) {
    if (d.expenses?.rent) draw(2, 150, 400, `$${d.expenses.rent}`, 9);
    if (d.expenses?.mortgage) draw(2, 150, 380, `$${d.expenses.mortgage}`, 9);
    if (d.expenses?.utilities) draw(2, 150, 360, `$${d.expenses.utilities}`, 9);
    if (d.expenses?.childcare) draw(2, 150, 340, `$${d.expenses.childcare}`, 9);
  }

  // Signature page (page 5, index 4)
  const sigPageIndex = Math.min(4, pages.length - 1);
  const sigY = pages.length > 4 ? 480 : 200;
  draw(sigPageIndex, 72, sigY, `${d.firstName || ''} ${d.lastName || ''}`.trim(), 10);
  draw(sigPageIndex, 350, sigY, today, 10);

  const pdfBytes = await pdfDoc.save();
  return pdfBytes;
}

export function downloadPDF(bytes, filename = 'PA-SNAP-Application.pdf') {
  const blob = new Blob([bytes], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}
