/**
 * Form registry — the single source of truth for every supported form.
 *
 * Each entry describes:
 *   - which PDF file to use (from pdf_files/)
 *   - which programs it covers
 *   - when it applies to a given user (applies())
 *   - how to map Gemini's extractedData to form field keys (adapt())
 *
 * Field coordinates live in the companion JSON files generated by tools/map-fields.js.
 * The filler in backend/services/pdf.js iterates the field list and draws each value.
 */

import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ── Helpers ────────────────────────────────────────────────────────────────────

function fmt(member) {
  if (!member) return '';
  const parts = [member.name || ''];
  return parts.join(' ').trim();
}

function normalizeFreq(freq = '') {
  const f = freq.toLowerCase();
  if (f.includes('week')) return 'Weekly';
  if (f.includes('bi') || f.includes('every 2')) return 'Bi-weekly';
  if (f.includes('month')) return 'Monthly';
  if (f.includes('annual') || f.includes('year')) return 'Yearly';
  return freq;
}

// ── SNAP Pennsylvania (Form C-257599) ─────────────────────────────────────────

const SNAP_PA = {
  id: 'snap-pa',
  name: 'Pennsylvania SNAP Application',
  programs: ['SNAP'],
  pdfFile: path.resolve(__dirname, '../pdf_files/SNAP_FORM_c_257599.pdf'),
  fieldsFile: path.resolve(__dirname, 'snap-pa-fields.json'),

  // SNAP screening applies to everyone
  applies: (_data) => true,

  /**
   * Map Gemini's rich nested extractedData to a flat { field_key: string } object.
   * Only keys that appear in snap-pa-fields.json will be drawn on the PDF.
   */
  adapt(data) {
    const d = data || {};
    const members = d.householdMembers || [];
    const income  = d.monthlyIncome    || [];

    const flat = {};

    // ── Contact info (page 3) ─────────────────────────────────────────────────
    flat.your_last_name  = d.lastName  || '';
    flat.your_first_name = d.firstName || '';
    flat.your_address    = d.address   || '';
    flat.county          = d.county    || '';
    flat.phone_number_home = d.phone   || '';

    // ── Household members (page 3, rows 1-8) ──────────────────────────────────
    members.slice(0, 8).forEach((m, i) => {
      const n = i + 1;
      flat[`household_member_${n}_name`]         = fmt(m);
      flat[`household_member_${n}_birthdate`]    = m.dob          || '';
      flat[`household_member_${n}_relationship`] = m.relationship || '';
    });

    // ── Income rows (page 4, rows 1-5) ────────────────────────────────────────
    income.slice(0, 5).forEach((inc, i) => {
      const n = i + 1;
      // Applicant is the income person unless a name is specified
      flat[`income_row${n}_person`]    = inc.person || d.firstName || '';
      flat[`income_row${n}_type`]      = inc.source    || '';
      flat[`income_row${n}_amount`]    = inc.amount    ? `$${inc.amount}` : '';
      flat[`income_row${n}_frequency`] = normalizeFreq(inc.frequency);
    });

    // ── Housing / expenses (page 5) ───────────────────────────────────────────
    const exp = d.expenses || {};
    if (exp.rent)       flat.rent_amount     = `$${exp.rent}`;
    if (exp.mortgage)   flat.mortgage_amount = `$${exp.mortgage}`;
    if (exp.utilities)  flat.expenses_other  = `Utilities: $${exp.utilities}`;
    if (exp.childcare)  flat.childcare_amount_per_month = `$${exp.childcare}`;

    return flat;
  },
};

// ── Medicaid Pennsylvania ──────────────────────────────────────────────────────
// Field map not yet generated — add when tools/map-fields.js is run on that PDF
const MEDICAID_PA = {
  id: 'medicaid-pa',
  name: 'Pennsylvania Medicaid Financial Eligibility',
  programs: ['Medicaid', 'CHIP'],
  pdfFile: path.resolve(__dirname, '../pdf_files/Medicaid Financial Eligibility_form.pdf'),
  fieldsFile: null, // TODO: run tools/map-fields.js on the Medicaid PDF

  applies: (data) => {
    const d = data || {};
    return !!(d.hasChildrenUnder5 || d.isPregnant || d.isPostpartum || d.isBreastfeeding);
  },

  adapt(_data) {
    // Placeholder until fieldsFile is generated
    return {};
  },
};

// ── Registry export ───────────────────────────────────────────────────────────

export const FORMS = [SNAP_PA, MEDICAID_PA];

/**
 * Return the subset of forms that apply to this user's data.
 * @param {object} extractedData   Gemini extractedData object
 * @returns {Array}                Matching form descriptors
 */
export function applicableForms(extractedData) {
  return FORMS.filter((f) => {
    if (f.fieldsFile === null) return false; // skip forms without a field map yet
    try { return f.applies(extractedData); } catch { return false; }
  });
}
